<?php

/**
 * Copyright 2021 Jeremy Presutti <Jeremy@Presutti.us>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** @var $content string */
/* @var $this View */

use Feast\Interfaces\ConfigInterface;
use Feast\Interfaces\ProfilerInterface;
use Feast\View;

echo $this->getDtd();
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <?= $this->getEncodingHtml(); ?>
    <?= $this->getTitle(); ?>
    <?= $this->getCss(); ?>
    <?= $this->getPreScripts(); ?>
    <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-16x16.png">
    <link rel="mask-icon" href="/icons/safari-pinned-tab.svg" color="#8972c5">
    <link rel="manifest" href="/icons/site.webmanifest">
    <meta name="msapplication-config" content="/icons/browserconfig.xml">
    <meta name="msapplication-TileColor" content="#8972c5">
    <meta name="theme-color" content="#ffffff">
</head>
<body>
<?php
include($content); ?>
<?= $this->getPostScripts(); ?>
<?php
if (\di(ConfigInterface::class)->getSetting('profiler')): ?>
    <p style="font-size:12px;">
        Total memory: <?= di(ProfilerInterface::class)->getReadableMemoryUsage(); ?><br/>
        Peak memory: <?= di(ProfilerInterface::class)->getReadablePeakMemoryUsage(); ?><br/>
        Page executed in <?= di(ProfilerInterface::class)->getTotalTime(); ?> seconds.
    </p>
<?php
endif; ?>
</body>
</html>
