name: PHPUnit MacOS

on: [push, pull_request]

jobs:
  build-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath
          coverage: xdebug
          tools: phpunit
      - name: Run PHPUnit
        run: phpunit -c FeastTests/githubphpunit.xml --coverage-clover coverage.xml
     